
all:
	make symbolic -C single/
	make symbolic -C rpc/
	make symbolic -C ws/
	make symbolic -C wsn/
	make symbolic -C wsne/
	make symbolic -C forward/
	make symbolic -C auth/
	make symbolic -C shopping/
	make symbolic -C conf/
	make symbolic -C loi/


clean:
	make clean -C single/
	make clean -C rpc/
	make clean -C ws/
	make clean -C wsn/
	make clean -C wsne/
	make clean -C forward/
	make clean -C auth/
	make clean -C shopping/
	make clean -C conf/
	make clean -C loi/

